### ISSUE TITLE
Inner pages: Gravity form 'Book your Appointment Today' some fields are not implemented as per design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Glen-Forrest-Dental#64]
![untitled-1frmm](https://cloud.githubusercontent.com/assets/13309730/12192308/7a5e5356-b603-11e5-8ac4-a775cfd03985.png)

**Comment by mahender-sowedane** [comment]
Can you give me an explanation why wontfix?
thanks!

**Comment by suniltitan** [comment]
![time and date field](https://cloud.githubusercontent.com/assets/14212899/12812331/a4f77ca0-cb57-11e5-9e4e-cf57882e1a88.png)
