### ISSUE TITLE
Forms : All forms should have a consistent Error message/prompts.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Glen-Forrest-Dental#66]
Affected forms:
Contact us
Book your Appointment Today

![error-msgs](https://cloud.githubusercontent.com/assets/13309730/12612079/529f0da2-c516-11e5-9ee1-6cdc61d9d139.png)

**Comment by suniltitan** [comment]
It is not a bug.Please go through the Bernard reference which is given below.


"It's not that there have to be error messages for every field, but there should be an error message which indicates that the form was not sent successfully at the top of the form."
                                                                                                                      -Bernard Salas
